name: Monitoreo y Despliegue

on:
  workflow_dispatch: 

jobs:
  pruebas-compatibilidad:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configuracion de Python
        uses: actions/setup-python@v4
      
      - name: Ejecución de pruebas
        run: echo "Configuración de Python exitosa | Version ${{ matrix.python-version }}"

  despliegue-produccion:
    runs-on: ubuntu-latest
    needs: pruebas-compatibilidad

    env:
      ENTORNO: "Produccion"

    steps:
      - name: Despliegue simulador
        run: echo "Todas las versiones de Python pasaron. Desplegando en $ENTORNO... "
      
      - name: Notificar error si falla
        if: ${{ failure() }}
        run: echo "Error, las pruebas fallaron en una de las versiones de Python"