name: validacion de pr

on: 
  pull_request:
    types: [opened, synchronize]

jobs: 
  validacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Saludar actor
        run: echo "Hola actor ${{ github.actor }}, todo funciona de maravilla!"

      - name: Verificacion
        run: echo "Verificando que todo esté en orden..."